services:
  # PostgreSQL Database
  - type: pserv
    name: document-assistant-db
    env: docker
    dockerfilePath: ./postgres/Dockerfile
    plan: starter
    envVars:
      - key: POSTGRES_DB
        value: document_assistant
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Redis Cache
  - type: redis
    name: document-assistant-redis
    plan: starter

  # MinIO Object Storage
  - type: pserv
    name: document-assistant-storage
    env: docker
    dockerfilePath: ./minio/Dockerfile
    plan: starter
    envVars:
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        generateValue: true

  # .NET API Service
  - type: web
    name: document-assistant-api
    env: docker
    dockerfilePath: ./dotnet-api/Dockerfile
    plan: starter
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: document-assistant-db
          property: connectionString
      - key: Redis__ConnectionString
        fromService:
          type: redis
          name: document-assistant-redis
          property: connectionString
      - key: MinIO__Endpoint
        value: http://document-assistant-storage:9000
      - key: MinIO__AccessKey
        value: minioadmin
      - key: MinIO__SecretKey
        fromService:
          type: pserv
          name: document-assistant-storage
          envVarKey: MINIO_ROOT_PASSWORD
      - key: PyProcessor__BaseUrl
        value: http://document-assistant-py-processor:8000

  # Python Processor Service
  - type: web
    name: document-assistant-py-processor
    env: docker
    dockerfilePath: ./py-processor/Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: document-assistant-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: document-assistant-redis
          property: connectionString
      - key: MINIO_ENDPOINT
        value: http://document-assistant-storage:9000
      - key: MINIO_ACCESS_KEY
        value: minioadmin
      - key: MINIO_SECRET_KEY
        fromService:
          type: pserv
          name: document-assistant-storage
          envVarKey: MINIO_ROOT_PASSWORD
      - key: GOOGLE_API_KEY
        sync: false

  # Frontend Service
  - type: web
    name: document-assistant-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://document-assistant-api.onrender.com