services:
  # PostgreSQL Database
  - type: pserv
    name: document-assistant-db
    env: docker
    dockerfilePath: ./postgres/Dockerfile
    plan: starter
    envVars:
      - key: POSTGRES_DB
        value: document_assistant
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Redis Cache
  - type: redis
    name: document-assistant-redis
    plan: starter

  # MinIO Object Storage
  - type: web
    name: document-assistant-storage
    env: docker
    dockerfilePath: ./minio/Dockerfile
    plan: starter
    envVars:
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
    healthCheckPath: /minio/health/live

  # .NET API Service
  - type: web
    name: ai-doc-viewer-api
    env: docker
    dockerfilePath: ./dotnet-api/Dockerfile
    plan: starter
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d2u0dfruibrs73f730qg-a.oregon-postgres.render.com;Port=5432;Database=docassistant_onbn;Username=appuser;Password=bTJKzRnQjpLZ8nfX3QHH07ZC9DhCNgbV;SSL Mode=Require
      - key: MINIO_ENDPOINT
        value: https://document-assistant-storage.onrender.com
      - key: MINIO_ACCESS_KEY
        value: minioadmin
      - key: MINIO_SECRET_KEY
        value: minioadmin
      - key: PY_BASE
        value: https://ai-doc-viewer-processor.onrender.com

  # Python Processor Service
  - type: web
    name: document-assistant-py-processor
    env: docker
    dockerfilePath: ./py-processor/Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        value: postgresql://appuser:bTJKzRnQjpLZ8nfX3QHH07ZC9DhCNgbV@dpg-d2u0dfruibrs73f730qg-a.oregon-postgres.render.com:5432/docassistant_onbn?sslmode=require
      - key: REDIS_URL
        fromService:
          type: redis
          name: document-assistant-redis
          property: connectionString
      - key: MINIO_ENDPOINT
        value: https://document-assistant-storage.onrender.com
      - key: MINIO_ACCESS_KEY
        value: minioadmin
      - key: MINIO_SECRET_KEY
        value: minioadmin
      - key: GEMINI_API_KEY
        sync: false

  # Frontend Service
  - type: web
    name: document-assistant-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-doc-viewer-api.onrender.com
      - key: REACT_APP_PROCESSOR_URL
        value: https://ai-doc-viewer-processor.onrender.com